name: rotarehber_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.14+42

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  glassmorphism: ^3.0.0
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  geolocator: ^11.0.0
  google_maps_flutter: 2.6.1 # SDK 3.3.0 ile uyumlu versiyon
  image_picker: ^1.0.4
  intl: ^0.18.1
  dio: ^5.4.3+1
  provider: ^6.1.2
  webview_flutter: ^4.8.0
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^11.0.0
  mobile_scanner: ^6.0.0
  firebase_analytics: ^12.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.0.0
  share_plus: ^10.0.0
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "../../ROTA 1024.png"
  min_sdk_size: 21 # android min sdk

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
